### ISSUE TITLE
Trying on Thinkpad L390

### ISSUE THREAD

**Issue by antoniomcr96** [Frank0xFF/ThinkPad-Hackintosh-Project#3]
I've been trying for days on Thinkpad L390 but unfortunally it get stuck on boot. I may be the hard drive (Samsung PM981) but it isn't sure.
I'm writing here because I'm wondering what your BIOS settings precisely were (Security and Startup section, BIOS interface should be the same) and if your system have booted since the beginning of your project or you needed a particular DSDT patch
Thanks in advance

**Comment by al-bonin** [comment]
On ThinkPad I just deactivated secure boot, made legacy boot I think, classic settings for hackintosh. I've had problems with UEFI. It is always different. On another device I was able to use UEFI.

You should always use your own DSDT to patch. Even after a BIOS update you cannot use your old DSDT.

You should make it first work, then patch DSDT. The original DSDT files of my own was able to boot my laptop, but had brightness problems and battery percentage was wrong.
